### ISSUE TITLE
Modal should exit when clicking outside the modal

### ISSUE THREAD

**Issue by CyboBrown** [CyboBrown/storiata-ceb#18]
Modal such as those that show up when opening an exercise and when confirming log out should exit when clicking outside the modal.

**Comment by ShySpaceSheep** [comment]
Looking into it.

**Comment by ShySpaceSheep** [comment]
Addressed in the latest pull request, please review #23 .

**Comment by CyboBrown** [comment]
Just finished checking and the fix has been successfully applied to all modals except for the "Confirm Logout" modal.
