### ISSUE TITLE
Text are cut off in certain elements and screens

### ISSUE THREAD

**Issue by CyboBrown** [CyboBrown/storiata-ceb#22]
Text are cut in specific elements and screens like such as the navigation buttons, profile view, and edit exercise view.

The images below show the bug taking place the profile page and edit exercise page respectively:
![image](https://github.com/user-attachments/assets/2dd6be6b-4a0b-495c-8adc-64c6eaecfc0f)
![image](https://github.com/user-attachments/assets/42ce4978-7124-483d-9711-b9d5ab8b18e2)

**Comment by ShySpaceSheep** [comment]
Replicating this bug in my environment will be difficult ATM. Previous stable versions were tested on `Small`, `Default`, and `Large` display sizes, and none of these configurations exhibited the same issue.

Will try testing with WebView or applying font scaling to investigate further.

**Comment by ShySpaceSheep** [comment]
@CyboBrown Currently cannot replicate in all different combinations of display sizes and font sizes. Preset screen dimensions have been tested for this specific bug but still unreproducible in:
- iPhone SE
- iPhone XR
- iPhone 12 Pro
- iPhone 14 Pro Max
- Pixel 7
- Samsung Galaxy S8+
- Samsung Galaxy S20 Ultra
- iPad Mini
- iPad Air
- iPad Pro
- Surface Pro 7
- Surface Duo
- Galaxy Z Fold 5
- Asus Zenbook Fold
- Samsung Galaxy A51/71
- Nest Hub
- Nest Hub Max

We've found occasional overlapping elements instead which are an issue for (absurd) extreme display and font sizes which is currently being looked at but element cutoffs are never reproduced: 
![image](https://github.com/user-attachments/assets/b224b702-cad1-48f7-b713-1718699ff90e)


Please include screen dimensions or other specific information that would help us narrow down reproducibility. Will mark this as `wontfix` if proven isolated to move on working on responsiveness on extreme screen dimensions.

**Comment by CyboBrown** [comment]
Added a fix in the latest pull request #24

**Comment by CyboBrown** [comment]
Bug is probably limited to certain devices and configurations (specifically Vivo V30e). Added necessary fixes regardless.
