### ISSUE TITLE
Improve sign up and sign in UI/UX

### ISSUE THREAD

**Issue by CyboBrown** [CyboBrown/storiata-ceb#35]
Sign up and sign in screens are not consistent with the rest of the application and doesn't have any sort of input error checking and error dialogs. Sign up also lacks necessary field such as username.

**Comment by ShySpaceSheep** [comment]
Looking into it now.

**Comment by ShySpaceSheep** [comment]
Addressed and resolved in PR #39. Please review it as soon as possible.
